inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

Rails:
  Enabled: true
  StyleGuideBaseURL: https://rails.rubystyle.guide

AllCops:
  NewCops: disable
  TargetRubyVersion: 2.7.1

RSpec/ImplicitExpect:
  Enabled: false
  AutoCorrect: false

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false
