inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

Rails:
  Enabled: true
  StyleGuideBaseURL: https://rails.rubystyle.guide

AllCops:
  NewCops: disable
